blog/urls.py
from django .urls import path

from blog.sitemaps import PostSitemap
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from . import views
from .feeds import LatestPostsFeed
app_name = 'blog'

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemaps'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('', views.post_list, name='post_list'),
    path('search/', views.post_search, name='post_search'),
    path('<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>', views.post_list, name='post_list_by_tag'),
    path('posts/<slug:category_slug>', views.post_list, name='post_list_by_category'),


]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('summernote/', include('django_summernote.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from ast import arg
from django.urls import reverse
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Category(models.Model):
    STATUS_CHOICE = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='created')
    image = models.ImageField(blank=True, upload_to='image/', null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=50, choices=STATUS_CHOICE, default='draft')

    published = PublishedManager()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    STATUS_CHOICE = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(blank=True, upload_to='image/')
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=50, choices=STATUS_CHOICE, default='draft')

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, related_name='posts', null=True)

    class Meta:
        ordering = ('-publish',)

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[
                           self.slug
                       ])

    @property
    def get_post_image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class meta:
        ordering = ('created',)

    def __str__(self) -> str:
        return f'Comment by {self.name} on {self.post}'


class Menu(models.Model):
    STATUS_CHOICE = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, )
    status = models.CharField(
        max_length=50, choices=STATUS_CHOICE, default='draft')

    published = PublishedManager()

    def __str__(self) -> str:
        return f'Menu: {self.title}'

blog/forms.py
from django import forms

from blog.models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import CommentForm, EmailPostForm, SearchForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchRank, SearchQuery
# Create your views here.


def post_list(request, tag_slug=None, category_slug=None):
    tag = None

    if category_slug:
        posts = Post.published.filter(category__slug=category_slug)
    elif tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = Post.published.filter(tags__in=[tag])
    else:
        posts = Post.published.all()

    paginator = Paginator(posts, 6)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/list.html', {
        'posts': posts,
        'page': page,
        'tag': tag
    })


def post_detail(request, post):
    post = get_object_or_404(Post, slug=post, status='published',)

    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count(
        'tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog/post/detail.html', {
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        # 'similar_posts': similar_posts
    })


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    try:
        if request.method == 'POST':
            print('aa: ', request.body)
            form = EmailPostForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                post_url = request.build_absolute_uri(post.get_absolute_url())
                subject = f"{cd['name']} recommends you read {post.title}"
                message = f"Read {post.title} at {post_url} \n\n {cd['name']} comments: {cd['comments']}"
                send_mail(subject, message, 'admin@myblog.com', [cd['to']])
                sent = True
        else:
            form = EmailPostForm()

    except ConnectionRefusedError as e:
        print('error: ', e)

    return render(request, 'blog/post/share.html', {
        'post': post,
        'form': form,
        'sent': sent
    })


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(search=search_query).order_by('-rank')

    return render(request,  'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

    <title>Stand CSS Blog by TemplateMo</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'blog/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'blog/assets/css/fontawesome.css' %} ">
    <link rel="stylesheet" href="{% static 'blog/assets/css/templatemo-stand-blog.css' %}">
    <link rel="stylesheet" href="{% static 'blog/assets/css/owl.css' %}">
<!--

TemplateMo 551 Stand Blog

https://templatemo.com/tm-551-stand-blog

-->
  </head>
<body>

<!-- Page Header-->
<!-- Main Content-->
    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
      <div class="jumper">
          <div></div>
          <div></div>
          <div></div>
      </div>
  </div>  
  <!-- ***** Preloader End ***** -->

  <!-- Header -->
{% include 'blog/layout/header.html' %}


  <!-- Page Content -->
  <!-- Banner Starts Here -->
  <div class="main-banner header-text">
    <div class="container-fluid">
      <div class="owl-banner owl-carousel">
      </div>
    </div>
  </div>
  <!-- Banner Ends Here -->


<div id="content">
  <section class="blog-posts">
    <div class="container">
      <div class="row">
        {% block content %}
        {% endblock  %}
        {% include "blog/layout/sidebar.html" %}
      </div>
    </div>
  </section>
</div>


<!-- Footer-->
{% include 'blog/layout/footer.html' %}

 <!-- Bootstrap core JavaScript -->
 <script src="{% static 'blog/assets/vendor/jquery/jquery.min.js' %}"></script>
 <script src="{% static 'blog/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

 <!-- Additional Scripts -->
 <script src="{% static 'blog/assets/js/custom.js' %}"></script>
 <script src="{% static 'blog/assets/js/owl.js' %}"></script>
 <script src="{% static 'blog/assets/js/slick.js' %}"></script>
 <script src="{% static 'blog/assets/js/isotope.js' %}"></script>
 <script src="{% static 'blog/assets/js/accordions.js' %} "></script>

 <script language = "text/Javascript"> 
   cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
   function clearField(t){                   //declaring the array outside of the
   if(! cleared[t.id]){                      // function makes it static and global
       cleared[t.id] = 1;  // you could use true and false, but that's more typing
       t.value='';         // with more chance of typos
       t.style.color='#fff';
       }
   }
 </script>
</body>
</html>

blog/templates/blog/layout/footer.html
<footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <ul class="social-icons">
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Behance</a></li>
            <li><a href="#">Linkedin</a></li>
            <li><a href="#">Dribbble</a></li>
          </ul>
        </div>
        <div class="col-lg-12">
          <div class="copyright-text">
            <p>Copyright 2020 Stand Blog Co.
                  
               | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a></p>
          </div>
        </div>
      </div>
    </div>
  </footer>

blog/templates/blog/layout/header.html
{% load blog_tags %}

<header class="">
    <nav class="navbar navbar-expand-lg">
      <div class="container">
        <a class="navbar-brand" href="{% url 'blog:post_list' %}"><h2>ThuanHiHi<em>.</em></h2></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
          {% get_categories as categories %}
            {% for category in categories  %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:post_list_by_category' category.slug  %}">{{category.title}}
                <span class="sr-only">(current)</span>
              </a>
            </li> 
           {% endfor %}
          </ul>
        </div>
      </div>
    </nav>
  </header>

blog/templates/blog/layout/nav.html
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="index.html">Start Bootstrap</a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive"
                aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto py-4 py-lg-0">
                <li class="nav-item">
                <a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a
                >
            </li>
            <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a
            >
        </li>
        <li class="nav-item">
        <a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a>
        </li>
    <li class="nav-item">
    <a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a
    >
</li>
</ul>
</div>
</div>
</nav>

blog/templates/blog/layout/pagination.html
        <!-- Pager-->
        {% comment %} <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div> {% endcomment %}

<div class="pagination">
    <span class="step-links">
      {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
      {% endif %}
      <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
      </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
      {% endif %}
    </span>
</div>

blog/templates/blog/layout/sidebar.html
{% load blog_tags %}

<div class="col-lg-4">
    <div class="sidebar">
      <div class="row">
        <div class="col-lg-12">
          <div class="sidebar-item search">
            <form id="search_form" name="gs" method="GET" action="{% url 'blog:post_search' %}">
              <input type="text" name="query" class="searchText" placeholder="type to search..." autocomplete="on">
            </form>
          </div>
        </div>
        <div class="col-lg-12">
            <div class="sidebar-item recent-posts">
              <div class="sidebar-heading">
                <p>
                    <a href="{% url 'blog:post_feed' %}">Subscribe to my RSS feed</a>
                </p>
              </div>
            </div>
        </div>
        {% comment %} <div class="col-lg-12">
          <div class="sidebar-item recent-posts">
            <div class="sidebar-heading">
              <h2>Recent Posts</h2>
            </div>
            {% show_latest_posts 3 %}
          </div>
        </div> {% endcomment %}
        <div class="col-lg-12">
          <div class="sidebar-item tags">
            <div class="sidebar-heading">
              <h2>Most commented posts</h2>
            </div>
            <div class="content">
                {% get_most_commented_posts as most_commented_posts %}
                <ul>
                    {% for post in most_commented_posts %}
                      <li>
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                      </li>
                    {% endfor %}
                </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-12">
          <div class="sidebar-item tags">
            <div class="sidebar-heading">
              <h2>TAGS</h2>
            </div>
            <div class="content">
                {% get_all_tags as tags %}
                <ul>
                    {% for tag in tags %}
                      <li>
                        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{tag.name}} ({{tag.post_num}})</a>
                      </li>
                    {% endfor %}
                </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}
    {{post.title}}
{% endblock %}
{% block content %}


<div class="col-lg-8">
    <div class="all-blog-posts">
      <div class="row">
        <div class="col-lg-12">
          <div class="blog-post">
            <div class="blog-thumb">
              <img src="assets/images/blog-post-02.jpg" alt="">
            </div>
            <div class="down-content">
              <a href="{{ post.get_absolute_url }}"><h4>{{post.title}}</h4></a>
              <ul class="post-info">
                <li><a href="#">{{post.author}}</a></li>
                <li><a href="#">{{post.created}}</a></li>
                <li><a href="#">{{post.comments.count}} Comment{{comments.count|pluralize}}</a></li> 
                
              </ul>
             {{post.body|markdown|safe}}
              <div class="post-options">
                <div class="row">
                  <div class="col-6">
                    <ul class="post-tags">
                        <li><i class="fa fa-tags"></i></li>
                        {% for tag in post.tags.all %}
                          <li>
                            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                            {{tag.name}}
                            </a>
                          {% if not forloop.last %}, {% endif %}
                        </li>
                        {% endfor %}
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>


        <div class="col-lg-12">
            {% get_similar_posts post as similar_posts  %}
            <h2>Similar posts</h2>
            {% for post in similar_posts %}
            <p>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </p>
            {% empty %}
                There are no similar posts yet.
            {% endfor %}
        </div>

        <div class="col-lg-12">
          <div class="sidebar-item comments">
            <div class="sidebar-heading">
                {% with comments.count as total_comments %}
                <h2>
                    {{total_comments}} comment{{total_comments|pluralize}}
                </h2>
                {% endwith %}
            </div>
            <div class="content">
              <ul>
                {% for comment in comments %}

                <li>
                    <div class="content-left">
                      <h6> Comment by {{comment.name}}<span>{{comment.created}}</span></h6>
                      <p>  {{comment.body|linebreaks}}</p>
                    </div>
                </li>
                <br>
            {% empty %}
            <p>There are no comments yet.</p>
            {% endfor %}
              </ul>
            </div>
          </div>
        </div>


        <div class="col-lg-12">
          <div class="sidebar-item submit-comment">
           
            <div class="content">
                {% if new_comment %}
                <h2>Your comment has been added</h2>
                {% else %}
                <h2>Add a new Comment</h2>
                <form method="post">
                    {{comment_form.as_p}}
                    {% csrf_token %}
                    <p><input type="submit" value="Add comment" class="btn btn-light" /></p>
                </form>
                {% endif %}

            </div>
          </div>
        </div>


      </div>
    </div>
  </div>

  
{% endblock %}

blog/templates/blog/post/latest_posts.html
<div class="content">
  <ul>
    {% for post in latest_posts %}

    <li><a href="{{ post.get_absolute_url }}">
      <p>{{ post.title }}</p>
      <span>{{post.created}}</span>
    </a></li>
  {% endfor %}
  </ul>
</div>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}
    My Blog
{% endblock title %}

{% block content %}
            <div class="col-lg-8">
              <div class="all-blog-posts">
                <div class="row">
                  {% for post in posts %}
                  <div class="col-lg-12">
                    <div class="blog-post">
                          <div class="blog-thumb ">
                            <img src="{{post.get_post_image_url}}" alt="" >
                          </div>

                          <div class="down-content">
                            <a href="{{post.get_absolute_url}}"><h4>{{post.title}}</h4></a>
                            <ul class="post-info">
                              <li><a href="#">{{post.author}}</a></li>
                              <li><a href="#">{{post.created}}</a></li>
                              <li><a href="#">{{post.comments.count}} comment{{post.comments.count|pluralize}}</a></li>
                            </ul>
                            {% comment %} <p>{{ post.body|truncatewords:50|safe }}</p> {% endcomment %}
                            <div class="post-options">
                              <div class="row">
                                <div class="col-6">
                                  <ul class="post-tags">
                                    <li><i class="fa fa-tags"></i></li>
                                    {% for tag in post.tags.all %}
                                      <li>
                                        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                                        {{tag.name}}
                                        </a>
                                      {% if not forloop.last %}, {% endif %}
                                    </li>
                                    {% endfor %}
                                  </ul>
                                </div>
                              </div>
                            </div>
                          </div>
                    </div>
                  </div>
                  {% endfor %}
                  <div class="col-lg-12">
                    <div class="main-button">
                      {% include 'blog/layout/pagination.html' with page=posts %} 
                    </div>
                  </div>
                </div>
              </div>
            </div>


{% endblock content %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}Search{% endblock %}
{% block content %}
  {% comment %} {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
        {% with results.count as total_results %}
            Found {{ total_results }} result{{ total_results|pluralize }}
        {% endwith %}
        </h3>
    {% for post in results %}
      <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
      {{ post.body|markdown|truncatewords_html:5 }}
    {% empty %}
      <p>There are no results for your query.</p>
{% endfor %}
    <p><a href="{% url 'blog:post_search' %}">Search again</a></p>
  {% else %}
    <h1>Search for posts</h1>

  {% endif %} {% endcomment %}

  <div class="col-lg-8">
    <div class="all-blog-posts">
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
          {% with results.count as total_results %}
            Found {{ total_results }} result{{ total_results|pluralize }}
          {% endwith %}
        </h3>
      <div class="row">
          {% for post in results %}
          <div class="col-lg-12">
            <div class="blog-post">
              {% comment %} <div class="blog-thumb">
                <img src="assets/images/blog-post-01.jpg" alt="">
              </div> {% endcomment %}
              <div class="down-content">
                {% comment %} <span>Lifestyle</span> {% endcomment %}
                <a href="{{post.get_absolute_url}}"><h4>{{post.title}}</h4></a>
                <ul class="post-info">
                  <li><a href="#">{{post.author}}</a></li>
                  <li><a href="#">{{post.created}}</a></li>
                  <li><a href="#">{{post.comments.count}} comment{{post.comments.count|pluralize}}</a></li>
                </ul>
                <p>{{ post.body|truncatewords:50 }}</p>
                <div class="post-options">
                  <div class="row">
                    <div class="col-6">
                      <ul class="post-tags">
                        <li><i class="fa fa-tags"></i></li>
                        {% for tag in post.tags.all %}
                          <li>
                            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                            {{tag.name}}
                            </a>
                          {% if not forloop.last %}, {% endif %}
                        </li>
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        <div class="col-lg-12">
          <div class="main-button">
            {% include 'blog/layout/pagination.html' with page=posts %} 
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}Share a post{% endblock %}
{% block content %}
{% include 'blog/layout/header.html' %}
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        {{sent}}
      {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
          "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
      {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
          {{ form.as_p }}
          {% csrf_token %}
          <input type="submit" value="Send e-mail">
        </form>
      {% endif %}
    </div>
</div>
{% endblock content %}